server.port=8082
spring.application.name=user-service

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/azarcafetero_users
spring.datasource.username=postgres
spring.datasource.password=azarcafetero123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true


